### ISSUE TITLE
Projects have a category

### ISSUE THREAD

**Issue by applegrain** [marlabrizel/the_pivot#58]
As a user, 
when I visit the home page and click on "Categories' in the nav bar
I see a drop down with all of the Categories
And when I click on a category in that drop down
I see all of the projects associated with the category.

When I visit a specific project, I can see which category it belongs to. 

As a company admin, 
when I create a new project, 
I can choose a category for it, 
when I click "Create", 
I am redirected to the project show page and can see which category it belongs to.

**Comment by Dmitry1007** [comment]
This is 3 user stories disguised as 1!

**Comment by marlabrizel** [comment]
To dos:
Update seed file with categories
db migration to add categories on project
Reseed projects with category id(?)
